services:

  postgres:
    image: postgres:18
    container_name: postgres-app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORTS}"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - data-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  ingestion:
    build:
      context: ./app/
      dockerfile: src/ingestion/Dockerfile
    container_name: ingestion-app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data-network
    volumes:
      - ./app/data:/app/data
    env_file:
      - .env
    environment:
      PG_HOST: ${POSTGRES_HOST}
      PG_PORT: ${POSTGRES_PORT}
      PG_DB: ${POSTGRES_DB}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}

  transform:
    container_name: dbt-transform
    build:
      context: ./app/
      dockerfile: src/incomes_dbt/Dockerfile
    env_file:
      - .env
    volumes:
        - ./app/src/incomes_dbt:/app/dbt
    environment:
        - DBT_PROFILES_DIR=/app/dbt
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      ingestion:
        condition: service_completed_successfully
    networks:
      - data-network
      
  dbt-docs:
    container_name: dbt-docs
    build:
      context: ./app/
      dockerfile: src/incomes_dbt/Dockerfile
    env_file:
      - .env
    volumes:
        - ./app/src/incomes_dbt:/app/dbt
    environment:
        - DBT_PROFILES_DIR=/app/dbt
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      transform:
        condition: service_completed_successfully
    command:
      bash -c "\
          dbt docs generate \
            --profiles-dir /app/dbt && \
          dbt docs serve \
              --profiles-dir /app/dbt \
              --port 8081 --host 0.0.0.0"
    networks:
      - data-network

volumes:
  postgres_data:

networks:
  data-network: